name: MapsPlugin
main: com.oresomecraft.maps.MapsPlugin
version: 1.0
depend: [OresomeBattles]
commands:
   enablemaps:
      description: Loads maps of a specific type
      usage: /<command> <battle/arcade>
      permission: oresomebattles.admin
      permission-message: You don't have <permission>
      
   guess:
      description: Guess a pictionary build
      usage: /<command> <pictionary guess>